# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewall', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
