# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mewall', '0010_auto_20160917_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'/home/gabrielle/Documents/code/gmemorial/static/img/uploads'),
        ),
    ]
